### PR TITLE
Genesis December Updates

### PR DESCRIPTION
**Pull request by orishim**
TODO
- [x] fill in all updates, add screenshots
- [ ] make proposal to Genesis for December funding

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Does this look good to you all? @orishim @mrrobot16 @cbrzn @pimato @tspoff @jpkcambridge @nickplace @namesty @xiphiness

**Comment by jpkcambridge** [comment]
@dOrgJelli We also applied to ConsenSys Grants for an "Open Raise" grant.  Should I add that too?

**Comment by dOrgJelli** [comment]
Sounds good to me if you'd like this information to be public and broadcasted to the Genesis DAO @jpkcambridge

**Comment by orishim** [comment]
The updates look great! Thanks @dOrgJelli !!

**Pull request merged**
