### PR TITLE
Minor Edits

### PR DESCRIPTION
**Pull request by dOrgJelli**
@mrrobot16 @orishim

### CODE REVIEW

**Comment by orishim** [comment]
Did you intend to bump the total workload up from 0.75 FT weeks (3 weeks x 0.25 FT) to 3 FT weeks (3 weeks x 1FT)? That's a very big difference.

**Comment by mrrobot16** [comment]
@orishim @dOrgJelli to my understanding is 1 FT for 3 weeks of work. Not 1 FT per week.

**Comment by orishim** [comment]
@dOrgJelli was there a reason you upped it from 3 weeks of quarter-time work to 3 weeks of full-time work?

**Comment by dOrgJelli** [comment]
Hey sorry for not including this in the description @mrrobot16 @orishim. I upped it because after looking into it I thought it was originally under scoped, as this requires custom UI inside Alchemy.

**Pull request merged**
